# Generated by Django 5.0.6 on 2024-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_task_assigned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(),
        ),
    ]
